# Generated by Django 5.0.6 on 2024-07-14 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0002_alter_creditcard_card_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('user', 'card_number')},
        ),
    ]
