# Generated by Django 5.0.6 on 2024-06-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/pictures/')),
                ('alt', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL')], max_length=4, null=True)),
                ('color', models.CharField(blank=True, choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('BLK', 'Black'), ('WHT', 'White'), ('YEL', 'Yellow'), ('ORN', 'Orange'), ('PUR', 'Purple'), ('PNK', 'Pink'), ('NVY', 'Navy'), ('GRY', 'Grey'), ('BRN', 'Brown'), ('TAN', 'Tan'), ('LBU', 'Light Blue'), ('DGY', 'Dark Grey'), ('LGR', 'Light Green'), ('DGR', 'Dark Green'), ('TEA', 'Teal'), ('OTH', 'Other')], max_length=3, null=True)),
                ('variations', models.TextField(blank=True, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
