# Generated by Django 5.0.6 on 2024-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('BLK', 'Black'), ('WHT', 'White'), ('YEL', 'Yellow'), ('ORN', 'Orange'), ('PUR', 'Purple'), ('PNK', 'Pink'), ('NVY', 'Navy'), ('GRY', 'Grey'), ('BRN', 'Brown'), ('TAN', 'Tan'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
