# Generated by Django 5.0.6 on 2024-06-29 04:23

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_picture_main_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=products.models.product_picture_upload_to),
        ),
    ]
