# Generated by Django 5.0.6 on 2024-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
